### ISSUE TITLE
Convert Tip calculator class to component

### ISSUE THREAD

**Issue by shagariboy** [shagariboy/tipcalculator-react-app#2]
Use the index.html file in this [repo](https://github.com/shagariboy/calculator-app-fc) as a reference

**Comment by RW2023** [comment]
I will take this one

**Comment by RW2023** [comment]
Css may need to be tweaked. Not sure if it going to be a "stateful" component so I left the constructor and state out. Just learning these concepts so let me know if my line of thinking is correct.
